name: paradrop-daemon
version: 0.42.0
summary: The ParaDrop daemon running at the extreme edge
description: |
  The ParaDrop deamon manages resources in the Wi-Fi routers and provides a virtualized environment for chutes.
  It also expose local environment information for chutes.

grade: devel
confinement: devmode

apps:
  paradrop:
    command: paradrop
    daemon: simple
    plugs:
      - network
      - network-bind
      - network-control
      - hardware-observe
      - system-observe
      - firewall-control
      - docker

  pdlog:
    command: pdlog

parts:
  localweb:
    plugin: dump
    source: localweb/

  pdlog:
    plugin: python
    python-version: python2
    source: tools/pdlog

  paradrop:
    plugin: python
    python-version: python2
    source: daemon
    build-packages:
      - python-dev
      - libffi-dev
    stage-packages:
      - libcurl4-openssl-dev
      - python-openssl

  dependencies:
    plugin: nil
    stage-packages:
      - dnsmasq
      - haproxy
    organize:
      usr/sbin: bin
      usr/lib: lib
    filesets:
      binaries:
        - bin/dnsmasq
        - bin/haproxy
      libraries:
        - lib/x86_64-linux-gnu/liblua5.3.so.*
    stage:
      - $binaries
      - $libraries
    prime:
      - $binaries
      - $libraries

  hostapd:
    plugin: dump
    source: https://paradrop.org/release/packages/hostapd-2.6.tar.bz2
    source-type: tar
    organize:
      hostapd: bin/hostapd
      hostapd_cli: bin/hostapd_cli
    filesets:
      binaries:
        - bin/hostapd
        - bin/hostapd_cli
    stage:
      - $binaries
    prime:
      - $binaries
